### ISSUE TITLE
(new kb.InlineKeyboard()).push() - TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by fabriciorby** [alexandercerutti/node-telegram-keyboard-wrapper#4]
Hello, I'm getting this error the very first time I try to push() something in my code.
If I try catch, and then try to push() again, it works.
I have no idea why.

`(new kb.InlineKeyboard()).push(0, { text: 'foo', callback_data: 'bar' });`

```
Sat, 07 Dec 2019 23:30:25 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. at internal\modules\cjs\loader.js:688:30

Warning: Push method does not return `this` anymore. Unexpected behaviour may happen. has been deprecated.
Debugger attached.
events.js:167
      throw er; // Unhandled 'error' event
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type undefined
    at validChunk (_stream_writable.js:258:10)
    at Socket.Writable.write (_stream_writable.js:292:21)
    at nodeDeprecate (c:\Users\fabri\Desktop\projects\personal\gado-bot-telegram\node_modules\deprecate\index.js:22:22)
    at deprecate (c:\Users\fabri\Desktop\projects\personal\gado-bot-telegram\node_modules\deprecate\index.js:11:3)
    at InlineKeyboard.push (c:\Users\fabri\Desktop\projects\personal\gado-bot-telegram\node_modules\node-telegram-keyboard-wrapper\src\reply_markup.js:95:9)
    at Object.<anonymous> (c:\Users\fabri\Desktop\projects\personal\gado-bot-telegram\broda-bot\broda-bot.js:10:27)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (c:\Users\fabri\Desktop\projects\personal\gado-bot-telegram\index.js:3:11)
    at Module._compile (internal/modules/cjs/loader.js:685:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
Emitted 'error' event at:
    at validChunk (_stream_writable.js:261:12)
    at Socket.Writable.write (_stream_writable.js:292:21)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
Waiting for the debugger to disconnect...
NodeError: The "chunk" argument must be one of type string or Buffer. Received type undefined
    at validChunk (_stream_writable.js:258:10)
    at Socket.Writable.write (_stream_writable.js:292:21)
    at nodeDeprecate (c:\Users\fabri\Desktop\projects\personal\gado-bot-telegram\node_modules\deprecate\index.js:22:22)
    at deprecate (c:\Users\fabri\Desktop\projects\personal\gado-bot-telegram\node_modules\deprecate\index.js:11:3)
    at InlineKeyboard.push (c:\Users\fabri\Desktop\projects\personal\gado-bot-telegram\node_modules\node-telegram-keyboard-wrapper\src\reply_markup.js:95:9)
    at Object.<anonymous> (c:\Users\fabri\Desktop\projects\personal\gado-bot-telegram\broda-bot\broda-bot.js:10:27)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (c:\Users\fabri\Desktop\projects\personal\gado-bot-telegram\index.js:3:11)
    at Module._compile (internal/modules/cjs/loader.js:685:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
Emitted 'error' event at:
    at validChunk (_stream_writable.js:261:12)
    at Socket.Writable.write (_stream_writable.js:292:21)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

**Comment by alexandercerutti** [comment]
Hi!
May I see your code just to try to understand it better?
Anyway, I don't know if I'll keep maintaining this library since I'm not developing bots anymore.

**Comment by fabriciorby** [comment]
Hi! Sure!

It goes like this:

```
const TelegramBot = require('node-telegram-bot-api');
const kb = require('node-telegram-keyboard-wrapper');
const twitterClient = require('../twitter-api/twitter');
const utils = require('./utils');

const token = process.env['TOKEN'];

const bot = new TelegramBot(token, { polling: true });
const inlineKeyboard = new kb.InlineKeyboard();

const buildInlineKeyboard = (async () => {

  try {
    (new kb.InlineKeyboard()).push(0, { text: 'foo', callback_data: 'bar' });
  } catch (e) {
    console.log("First initialization crashes.")
  }

  for (const id of Object.values(utils.twitterUsers)) {
    const username = await twitterClient.getUsernameById(id);
    if (inlineKeyboard.length == 0) {
      inlineKeyboard.addRow()
    }
    if (inlineKeyboard.rowLength(inlineKeyboard.length - 1) == 2) {
      inlineKeyboard.addRow({ text: username, callback_data: username })
    } else {
      inlineKeyboard.push(inlineKeyboard.length - 1, { text: username, callback_data: username })
    }
  };

});

buildInlineKeyboard();
```

I hope it helps, if you need more code I can open the project for a while :)

**Comment by alexandercerutti** [comment]
I think that might be some kind of problem with my code... I probably do not perform checks on rows availability or such.
Instead of pushing, just use something like:

```
const inlineKeyboard = new kb.InlineKeyboard({ text: 'foo', callback_data: 'bar' });
```

Anyway, why are you pushing that data on a new instance of the class?

**Comment by fabriciorby** [comment]
> Anyway, why are you pushing that data on a new instance of the class?

Just forcing the error to be thrown, it would occur anywway even if it was:
`inlineKeyboard.push(0, { text: 'foo', callback_data: 'bar' })`
:(

By the way, it happens even if:
```
inlineKeyboard.addRow()
inlineKeyboard.push(0, { text: 'foo', callback_data: 'bar' });
```

It just won't push the first time, only if I push() it again...

**Comment by alexandercerutti** [comment]
Okay so, there's a problem here:
`.addRow` shouldn't be empty as parameters: it adds all the elements to the current row. So it expects at least an object. This because I did this library on my own needs and not implemented correctly checks.

So, can you try to add directly `{ text: 'foo', callback_data: 'bar' }` in `addRow`?

**Comment by fabriciorby** [comment]
> So, can you try to add directly `{ text: 'foo', callback_data: 'bar' }` in `addRow`?

Sure, and `addRow` always does work!
The only problem is with the very first push()...

I'm trying to debug but I am not into ts. :'(

**Comment by alexandercerutti** [comment]
I don't think there's something you can do. Just use push only if there are rows.
As I said before, I'll probably never put my hands again on this, because I don't do bots anymore.

**Comment by fabriciorby** [comment]
That's ok. I'll keep it with that terrible try catch lol.
Thanks!

**Comment by alexandercerutti** [comment]
Hey there @fabriciorby,
I just wanted you to know that, after a year, I've rewritten this library and, in the next few hours, I'll publish it.
It is simpler now and quite different. I don't know if you are still using this.

Have a nice day!

**Comment by fabriciorby** [comment]
Hey @alexandercerutti,

Yeah, I've used it [here](https://github.com/fabriciorby/twitter-bot-telegram) and in another private project.

Good to know, I'll take a look at your new version, thank you!
